name: "Fetch: ProtonVPN"
on:
  push:
    paths:
      - ".github/workflows/fetch-protonvpn.yml"
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install jq
      - name: Download and process
        run: |
          curl https://api.protonmail.ch/vpn/logicals | jq '.LogicalServers[].Servers[].ExitIP' -r | sort -n > /tmp/protonvpn.txt
      - name: Merge Lists
        run: |
          perl ./helpers/cleanup.pl /tmp/protonvpn.txt > protonvpn.txt
      - name: Test generated lists
        run: |
          if [[ $(grep ^0. protonvpn.txt | wc -l) != "0" ]]; then
            echo "Lists can not contain 0.0.0.0/8"
            exit 1
          fi
          if [[ $(grep ^127. protonvpn.txt | wc -l) != "0" ]]; then
            echo "Lists can not contain 12.0.0.1/8"
            exit 1
          fi

          ips_covered=$(awk -F/ 'BEGIN{a=0}{if($2==""){a+=1}else{a+=2^(32-$2)}}END{print a}' protonvpn.txt)
          if [[ "$ips_covered" -lt 1000 ]]; then
            echo "Too few addresses covered ($ips_covered)"
            exit 1
          fi
          if [[ "$ips_covered" -gt 3000 ]]; then
            echo "Too many addresses covered"
            exit 1
          fi

          mv protonvpn.txt input/ips/protonvpn.txt
      - name: Commit and push output of protonvpn.txt
        run: |-
          git diff
          git config --global user.email "automated@humblefox.com"
          git config --global user.name "listbuilder"
          git add -A
          git commit -m "Update protonvpn.txt" || exit 0
          git push
